### ISSUE TITLE
could you provide the format (or a example) of train data?

### ISSUE THREAD

**Issue by njuzrs** [fionn-mac/A-Persona-Based-Neural-Conversation-Model#1]
quite nice code! could you provide a example of train data file to help me deeply understand the code? thanks!

**Comment by fionn-mac** [comment]
Hey!

This model isn't complete (yet), but we've started work on it again.
In the meanwhile,  the dataset can be found here: https://github.com/jiweil/Neural-Dialogue-Generation
All credits go to the original authors for the tremendous work they've done on the dataset.

Sorry for the late response, and I hope the provided link proves to be useful!
